### ISSUE TITLE
App requires "my key" when encrypting for a contact

### ISSUE THREAD

**Issue by zouden** [MarinX/yap#10]
**Describe the bug**
I can't encrypt a message to a contact unless I select one of my own keys first.

**To Reproduce**
Write a message and encrypt it with a contact's key, but leave the "my key" field blank.

**Expected behavior**
The text should be encrypted with the recipient's key.

Instead, the app demands that "my key" is selected, even though only 1 key is needed to encrypt a message.

**Comment by MarinX** [comment]
Hi @zouden , 
So, if I encrypt a message without my key (I dont know how is this possible), how do you plan to decrypt it, since there is no key(public) ?

Did you mean, if you only have 1 private key, to be auto-selected?

**Comment by zouden** [comment]
If you want to encrypt a message for me, you would use my public key.

**Comment by MarinX** [comment]
By default the app uses message signing to encrypt message as most of the PGP software will always check the header file to verify the signature. 
I wil add this as an option over the weekend.

**Comment by zouden** [comment]
I see, that explains the behaviour. I've never signed a PGP message (intentionally) so I didn't know about this feature.

**Comment by MarinX** [comment]
hey @zouden , I included the option to create unsigned PGP message. Also, there is a warning about it as most of the PGP software will not able to decrypt it(because by default they will look at the signature header), but, if you are using cli command (e.g. gpg), you can decrypt it without specify the sign option, so, just a warning that a second party will not be able to decrypt it.
The update is now live on play store.

Closing this issue.

**Comment by zouden** [comment]
Perfect, thanks very much!
